version: '3.8'

services:
  app:
    build: .
    volumes:
      - ${PWD}:/app/user-service
    ports:
      - "8080:8080"
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./backup:/var/lib/mysql:rw
