version: '3.8'

services:
  app:
    build: .
    volumes:
      - ${PWD}:/app/job-scheduler-service
      - /usr/src/app/node_modules
    ports:
      - "8081:8081"
    command: ["npm", "run", "start:dev"]
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./backup:/var/lib/mysql:rw
